use anyhow::Error;

fn main() -> Result<(), Error>{
    robusta::run()
}
